### ISSUE TITLE
Missing prompt to use virtual env

### ISSUE THREAD

**Issue by MattAtkinson** [ARMmbed/ref-wem-webapp#3]
Tested on a fresh Ubuntu 16.04 after doing apt update+upgrade. VM running in virtualbox on Windows 10

./manage.py loaddata testauth – this doesn’t work due to missing Django.core.management. presumably as we are no longer working in the virtual env? I used ‘workon’ again to work around this. I guess the testing part should start with “Open a new terminal, run workon…”

**Comment by mbanders** [comment]
Fixed just now with this commit: https://github.com/ARMmbed/ref-wem-webapp/commit/0091803221084421f7f7120e6c77376e5cc9bbcc
